require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'spec/spec_helper.rb'

Layout/LineLength:
  Max: 100
  Enabled: true
Metrics/MethodLength:
  Max: 15
Metrics/BlockLength:
  Exclude:
    - 'spec/*'